### ISSUE TITLE
On first open, dropdown menu doesn't scroll to selected item until after animation

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-dropdown-menu#144]
Example: 200 items, with the 100th item selected: https://jsfiddle.net/mgiuffrida/8je4wo0d

Expected: when opening the dropdown menu, the 100th item is in the middle of the view, like a `<select>`

Actual: the first time the dropdown menu is opened, the list is shown starting at 0, and snaps down to the 100th item after the entire animation completes

**Comment by peteblois** [comment]
Additional jank because the scrollbars don't appear until the animation has completed.

**Comment by mgiuffrida** [comment]
it's also silly that the vertical scrollbar causes a horizontal scrollbar to be shown

@notwaldorf  @bicknellr  are these issues with `paper-dropdown-menu` or `paper-listbox`?

**Comment by valdrinkoshi** [comment]
This is related to this other issue on `iron-overlay-behavior` https://github.com/PolymerElements/iron-overlay-behavior/issues/201
It will get fixed once that issue is fixed (using the PR https://github.com/PolymerElements/iron-overlay-behavior/pull/202) https://jsfiddle.net/wef9087f/
Will close this as we already have that other issue for tracking the bug.
