### ISSUE TITLE
<paper-dropdown-menu> does not apply initial selection

### ISSUE THREAD

**Issue by nick211** [PolymerElements/paper-dropdown-menu#42]
Example:

    <template>
      <paper-dropdown-menu>
        <paper-menu class="dropdown-content" selected="B" attr-for-selected="value">
          <paper-item value="A">test</paper-item>
          <paper-item value="B">[[abc]]</paper-item>
        </paper-menu>
      </paper-dropdown-menu>
    </template>
  </dom-module>

    <script>
      Polymer({is: 'my-widget',
        properties: {
          abc: {
            type: String,
            value: 'abc',
          }
        },
      });
    </script>

Actual behavior: nothing is selected in the dropdown.
Expected behavior: item with value="B" ("abc") is selected in the dropdown.

**Comment by Compufreak345** [comment]
@nick211 Did you find any workaround/solution for this issue?

**Comment by zmoshansky** [comment]
+1, Potentially Related to #23. (Although the fix I used there doesn't seem to work).

I've tried debugging this behaviour and in my case the `paper-listbox` has the correct values (`selectedItem`, `selected` return the correct results). The `paper-dropdown-menu` label is set to blank due to an `on-iron-deselect` event being fired. When calling `paper-dropdown-menu.value` it returns the correct values and everything, so the issue appears to be cosmetic.

However, when debugging, it seems like the order changes as it tends to function correctly if I have a breakpoint set in each of the following. This suggests to me that there is some sort of race condition going on.

```
        _onIronSelect: function(event) {
          this._setSelectedItem(event.detail.item);
        },

        /**
         * A handler that is called when `iron-deselect` is fired.
         *
         * @param {CustomEvent} event An `iron-deselect` event.
         */
        _onIronDeselect: function(event) {
          this._setSelectedItem(null);
        },
```

**Comment by cdata** [comment]
Hi, I believe that this bug is fixed. If it is still broken for you, please re-open with a reduced test case!

For more details, please refer to our [contributing guidelines](https://github.com/PolymerElements/paper-dropdown-menu/blob/master/CONTRIBUTING.md).

**Comment by Compufreak345** [comment]
I can confirm that for me the issue is resolved.
