### ISSUE TITLE
The paper-input show the float animation when select an option and an option is already selected

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-dropdown-menu#99]
You can reproduce it in the [oficial demo](https://elements.polymer-project.org/elements/paper-dropdown-menu?view=demo).

In the "No underline (menu from bottom)" example can be seen very well.

**Comment by cdata** [comment]
Unfortunately, the description is not sufficiently clear for me to understand what the problem is. Can you re-open with a clear description of what you expected and what is happening? The float animation problem in your title is not reproducing for me, so I feel like I just don't understand the issue.

For more details on filing issues, please refer to our [contributing guidelines](../blob/master/CONTRIBUTING.md).

**Comment by abdonrd** [comment]
I see this no longer happens. It must be fixed. Thanks @cdata!

**Comment by abdonrd** [comment]
@cdata oh! Now I've caught in the master branch.

![feb 03 2016 13 02](https://cloud.githubusercontent.com/assets/1007051/12782356/10db7b66-ca7b-11e5-8f32-aec553ee3c6e.gif)

The `paper-input` show the float animation when select an option and an option is already selected.
